default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: "netflics"
  password: "grupo1"

development:
  <<: *default
  database: netflics_development

test:
  <<: *default
  database: netflics_test

production:
  <<: *default
  database: netflics_production
